config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pages
  resources :companies
  resources :quotes do
    resources :line_item_dates, except: [:index, :show] do
      resources :line_items, except: [:index, :show]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users, dependent: :destroy
  has_many :quotes, dependent: :destroy

  validates :name, presence: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :line_item_date

  validates :name, presence: true
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :unit_price, presence: true, numericality: { greater_than: 0 }

  delegate :quote, to: :line_item_date

  def total_price
    quantity * unit_price
  end
end

app/models/line_item_date.rb
class LineItemDate < ApplicationRecord
  has_many :line_items, dependent: :destroy
  belongs_to :quote

  validates :date, presence: true, uniqueness: { scope: :quote_id }
  scope :ordered, -> { order(date: :asc) }

  def previous_date
    quote.line_item_dates.ordered.where('date < ?', date).last
  end
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/quote.rb
class Quote < ApplicationRecord
  has_many :line_item_dates, dependent: :destroy
  has_many :line_items, through: :line_item_dates
  belongs_to :company

  validates :name, presence: true

  scope :ordered, -> { order(id: :desc) }

  broadcasts_to ->(quote) { [quote.company, 'quotes'] }, inserts_by: :prepend

  def total_price
    line_items.sum(&:total_price)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable

  belongs_to :company

  def name
    email.split('@').first.capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, unless: :devise_controller?

  private

  def current_company
    @current_company ||= current_user.company if user_signed_in?
  end

  helper_method :current_company
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
end

app/controllers/line_item_dates_controller.rb
class LineItemDatesController < ApplicationController
  before_action :set_quote
  before_action :set_line_item_date, only: %i[edit update destroy]

  def new
    @line_item_date = @quote.line_item_dates.new
  end

  def create
    @line_item_date = @quote.line_item_dates.new(line_item_date_params)

    if @line_item_date.save
      respond_to do |format|
        format.html { redirect_to quote_path(@quote), flash: { success: 'Date was successfully created.' } }
        format.turbo_stream { flash.now[:success] = 'Date was successfully created.' }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @line_item_date.update(line_item_date_params)
      respond_to do |format|
        format.html { redirect_to quote_path(@quote), flash: { notice: 'Date was successfully updated.' } }
        format.turbo_stream { flash.now[:notice] = 'Date was successfully updated.' }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @line_item_date.destroy
    respond_to do |format|
      format.html { redirect_to quote_path(@quote), flash: { alert: 'Date was successfully destroyed.' } }
      format.turbo_stream { flash.now[:alert] = 'Date was successfully destroyed.' }
    end
  end

  private

  def line_item_date_params
    params.require(:line_item_date).permit(:date)
  end

  def set_quote
    @quote = current_company.quotes.find(params[:quote_id])
  end

  def set_line_item_date
    @line_item_date = @quote.line_item_dates.find(params[:id])
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_quote
  before_action :set_line_item_date
  before_action :set_line_item, only: %i[edit update destroy]

  def new
    @line_item = @line_item_date.line_items.new
  end

  def create
    @line_item = @line_item_date.line_items.new(line_item_params)
    if @line_item.save
      respond_to do |format|
        format.html { redirect_to quote_path(@quote), flash: { success: 'Item was successfully created.' } }
        format.turbo_stream { flash.now[:success] = 'Item was successfully created.' }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @line_item.update(line_item_params)
      respond_to do |format|
        format.html { redirect_to quote_path(@quote), flash: { notice: 'Item was successfully updated.' } }
        format.turbo_stream { flash.now[:notice] = 'Item was successfully updated.' }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to quote_path(@quote), flash: { alert: 'Date was successfully destroyed.' } }
      format.turbo_stream { flash.now[:alert] = 'Date was successfully destroyed.' }
    end
  end

  private

  def set_quote
    @quote = current_company.quotes.find(params[:quote_id])
  end

  def line_item_params
    params.require(:line_item).permit(:name, :description, :quantity, :unit_price)
  end

  def set_line_item_date
    @line_item_date = @quote.line_item_dates.find(params[:line_item_date_id])
  end

  def set_line_item
    @line_item = @line_item_date.line_items.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home; end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: %i[show edit update destroy]

  def index
    @quotes = current_company.quotes.ordered
  end

  def show
    @line_item_dates = @quote.line_item_dates.includes(:line_items).ordered
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = current_company.quotes.build(quote_params)

    if @quote.save
      respond_to do |format|
        format.html { redirect_to quotes_path, flash: { success: 'Quote was successfully created.' } }
        format.turbo_stream { flash.now[:success] = 'Quote was successfully created.' }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @quote.update(quote_params)
      respond_to do |format|
        format.html { redirect_to quotes_path, flash: { notice: 'Quote was successfully updated.' } }
        format.turbo_stream { flash.now[:notice] = 'Quote was successfully updated.' }
      end
    else
      # flash[:error] = @quote.errors.full_messages.to_sentence.capitalize
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_path, flash: { alert: 'Quote was successfully destroyed.' } }
      format.turbo_stream { flash.now[:alert] = 'Quote was successfully destroyed.' }
    end
  end

  private

  def set_quote
    @quote = current_company.quotes.find(params[:id])
  end

  def quote_params
    params.require(:quote).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_turbo_stream_flash_messages
    turbo_stream.prepend 'flash', partial: 'layouts/flash'
  end

  def form_error_notification(object)
    return unless object.errors.any?

    tag.div class: "flash flash_message min-w-0 max-w-max py-2 px-3 bg-red-50
     mb-5 text-red-500 font-medium rounded-lg inline-block" do
      object.errors.full_messages.to_sentence.capitalize
    end
  end

  def nested_dom_id(*args)
    args.map { |arg| arg.respond_to?(:to_key) ? dom_id(arg) : arg }.join('_')
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/line_item_dates_helper.rb
module LineItemDatesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="flash__message"
  data-controller="removals"
  data-action="animationend->removals#remove">
    <% if type == "success" %>
      <div class="min-w-0 max-w-max py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block">
        <%= msg %>
      </div>
    <% elsif type == "notice" %>
      <div class="min-w-0 max-w-max py-2 px-3 bg-yellow-50 mb-5 text-yellow-500 font-medium rounded-lg inline-block">
        <%= msg %>
      </div>
    <% else %>
      <div class="min-w-0 max-w-max py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block">
        <%= msg %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="flex items-center px-2 gap-2 bg-[#eee]">
  <% if user_signed_in? %>
    <div class="mr-auto font-bold">
      <%= current_company.name %>
    </div>
    <div class="ml-auto font-bold">
      <%= current_user.name %>
    </div>
    <%= button_to "Sign out",
                  destroy_user_session_path,
                  method: :delete,
                  class: "border-2 border-black px-1 inline-block py-1 rounded-md bg-origin-border bg-transparent
    border-2 border-black p-5 m-2 font-bold no-underline cursor-pointer
    hover:shadow-[0_0_20px_#eee] hover:text-red-600 hover:bg-[right_center] focus:text-red-600 active:text-red-600
                       rounded-[10px] transition-all duration-500" %>
  <% else %>
    <%= link_to "Sign in",
                new_user_session_path,
                class: "inline-block py-1 rounded-md bg-origin-border bg-transparent
    border-2 border-black p-5 m-2 font-bold no-underline cursor-pointer
    hover:shadow-[0_0_20px_#eee] hover:text-blue-600 hover:bg-[right_center] focus:text-blue-600 active:text-blue-600
                       rounded-[10px] transition-all duration-500 ml-auto" %>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quote-Editor-Hotrails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= hotwire_livereload_tags if Rails.env.development? %>
  </head>
  <body>
    <%= render "layouts/navbar" %>
    <div id="flash" class="flash">
      <%= render "layouts/flash" %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/line_item_dates/_form.html.erb
<%= simple_form_for [quote, line_item_date], html: { class: "flex items-center flex-wrap align-center gap-2.5 shadow-md line-item-date" } do |f| %>
  <% if line_item_date.errors.any? %>
    <%= form_error_notification(line_item_date) %>
  <% end %>
  <%= f.input :date, html5: true,
   input_html: { autofocus: true,
   class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:outline-none focus:shadow-[0_0_0_2px_#A3D1FF] focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 transition-shadow duration-300" },
   wrapper_html: { class: 'flex-1' },
  label_html: { class: "sr-only" } %>
  <%= link_to "Cancel", quote_path(quote), class: "inline-block bg-origin-border bg-transparent border-2 p-1 m-2 font-bold cursor-pointer p-0 rounded-1.5
                         transition ease-in-out duration-500 text-black bg-[#00000021] hover:bg-[#00000066] border-black" %>
  <%= f.submit class: "py-2 px-4 text-white bg-gradient-to-r from-[#e52d27] via-[#b31217] to-[#e52d27] bg-[length:200%_auto]
                       hover:shadow-[0_0_20px_#eee] hover:text-white hover:bg-[right_center] focus:text-white active:text-white
                       rounded-[10px] transition-all duration-500" %>
<% end %>

app/views/line_item_dates/_line_item_date.html.erb
<%= turbo_frame_tag line_item_date do %>
  <div class="line-item-date">
    <%= turbo_frame_tag dom_id(line_item_date, :edit) do %>
      <div class="p-7">
        <div class="flex items-center justify-between gap-2">
          <h2 class="text-xl font-bold underline-text">
            <%= l(line_item_date.date, format: :long) %>
          </h2>
          <div class="flex md:text-2xl gap-2">
            <%= button_to [quote, line_item_date],
                    method: :delete,
                    form: { data: { turbo_confirm: "Click \"OK\" to confirm deletion." } },
                    class: "flex flex-col items-center justify-center px-4 py-2 bg-gray-200 hover:bg-gray-300 text-gray-800 text-sm font-medium rounded-md" do %>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16"> <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/> <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/> </svg>
              Delete
            <%end%>
            <%= link_to [:edit, quote, line_item_date],
                  class: "flex flex-col items-center justify-center px-4 py-2 bg-gray-200 hover:bg-gray-300 text-gray-800 text-sm font-medium rounded-md" do %>
              <svg width="24" stroke-width="1.5" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M20 12V5.74853C20 5.5894 19.9368 5.43679 19.8243 5.32426L16.6757 2.17574C16.5632 2.06321 16.4106 2 16.2515 2H4.6C4.26863 2 4 2.26863 4 2.6V21.4C4 21.7314 4.26863 22 4.6 22H11" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/> <path d="M8 10H16M8 6H12M8 14H11" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/> <path d="M16 5.4V2.35355C16 2.15829 16.1583 2 16.3536 2C16.4473 2 16.5372 2.03725 16.6036 2.10355L19.8964 5.39645C19.9628 5.46275 20 5.55268 20 5.64645C20 5.84171 19.8417 6 19.6464 6H16.6C16.2686 6 16 5.73137 16 5.4Z" fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/> <path d="M17.9541 16.9394L18.9541 15.9394C19.392 15.5015 20.102 15.5015 20.5399 15.9394V15.9394C20.9778 16.3773 20.9778 17.0873 20.5399 17.5252L19.5399 18.5252M17.9541 16.9394L14.963 19.9305C14.8131 20.0804 14.7147 20.2741 14.6821 20.4835L14.4394 22.0399L15.9957 21.7973C16.2052 21.7646 16.3988 21.6662 16.5487 21.5163L19.5399 18.5252M17.9541 16.9394L19.5399 18.5252" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/>
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
              </svg>
              Edit
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <div class="line-item-date__body">
      <div class="line-item line-item--header">
        <div class="line-item__name">Article</div>
        <div class="line-item__quantity">Quantity</div>
        <div class="line-item__price">Price</div>
        <div class="line-item__actions"></div>
      </div>
      <%= turbo_frame_tag nested_dom_id(line_item_date, "line_items") do %>
        <%= render line_item_date.line_items, quote: quote, line_item_date: line_item_date %>
      <% end %>
      <%= turbo_frame_tag nested_dom_id(line_item_date, LineItem.new) %>
      <div class="line-item-date__footer">
        <%= link_to "Add item",
                    [:new, quote, line_item_date, :line_item],
                     data: { turbo_frame: nested_dom_id(line_item_date, LineItem.new) },

                    class: "btn btn--primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/line_item_dates/create.turbo_stream.erb
<%= turbo_stream.update LineItemDate.new, "" %>
<% if previous_date = @line_item_date.previous_date %>
  <%= turbo_stream.after previous_date do %>
    <%= render @line_item_date, quote: @quote %>
  <% end %>
<% else %>
  <%= turbo_stream.prepend "line_item_dates" do %>
    <%= render @line_item_date, quote: @quote %>
  <% end %>
<% end %>
<%= render_turbo_stream_flash_messages %>

app/views/line_item_dates/destroy.turbo_stream.erb
<%= turbo_stream.remove @line_item_date %>
<%= render_turbo_stream_flash_messages %>
<%= turbo_stream.update dom_id(@quote, :total) do %>
  <%= render "quotes/total", quote: @quote %>
<% end %>

app/views/line_item_dates/edit.html.erb
<main class="flex flex-col mx-auto my-4 px-2 sm:px-1 sm:max-w-[60rem]">
  <%= link_to sanitize("&larr; Back to quote"), quote_path(@quote) %>
  <div class="flex justify-between gap-3 mt-4 mb-6 flex-wrap sm:mb-8">
    <h1>Edit date</h1>
  </div>
  <%= render "form", quote: @quote, line_item_date: @line_item_date %>
</main>

app/views/line_item_dates/new.html.erb
<main class="flex flex-col mx-auto my-4 px-2 sm:px-1 sm:max-w-[60rem]">
  <%= link_to sanitize("&larr; Back to quote"), quote_path(@quote) %>
  <div class="flex justify-between gap-3 mt-4 mb-6 flex-wrap sm:mb-8">
    <h1>New date</h1>
  </div>
  <%= turbo_frame_tag @line_item_date do %>
    <%= render "form", quote: @quote, line_item_date: @line_item_date %>
  <% end %>
</main>

app/views/line_item_dates/update.turbo_stream.erb
<%= turbo_stream.remove @line_item_date %>

<% if previous_date = @line_item_date.previous_date %>
  <%= turbo_stream.after previous_date do %>
    <%= render @line_item_date, quote: @quote %>
  <% end %>
<% else %>
  <%= turbo_stream.prepend "line_item_dates" do %>
    <%= render @line_item_date, quote: @quote %>
  <% end %>
<% end %>

<%= render_turbo_stream_flash_messages %>

app/views/line_items/_form.html.erb
<%= simple_form_for [quote, line_item_date, line_item],
                    html: { class: "form line-item line-item--form" } do |f| %>
  <%= form_error_notification(line_item) %>
  <%= f.input :name,
              placeholder: "Name of the article",
              wrapper_html: { class: "line-item__name" },
              label_html: { class: "sr-only" },
              input_html: { autofocus: true } %>
  <%= f.input :quantity,
              placeholder: "Quantity",
              wrapper_html: { class: "line-item__quantity" },
              label_html: { class: "sr-only" } %>
  <%= f.input :unit_price,
              placeholder: "Price",
              wrapper_html: { class: "line-item__price" },
              label_html: { class: "sr-only" } %>
  <%= f.input :description,
              wrapper_html: { class: "line-item__description" },
              label_html: { class: "sr-only" } %>
  <div class="line-item__actions">
    <%= link_to quote_path(quote), class: "flex flex-col items-center justify-center px-4 py-2  hover:bg-gray-300 text-gray-800 text-sm font-medium rounded-md" do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-x-square-fill" viewBox="0 0 16 16" id="IconChangeColor"> <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm3.354 4.646L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 1 1 .708-.708z" id="mainIconPathAttribute" fill="#ff0000"></path> </svg>
    <% end %>
    <%= button_tag(type: 'submit', class: "flex flex-col items-center justify-center px-4 py-2  hover:bg-gray-300 text-gray-800 text-sm font-medium rounded-md") do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-check-square-fill" viewBox="0 0 16 16" id="IconChangeColor"> <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm10.03 4.97a.75.75 0 0 1 .011 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.75.75 0 0 1 1.08-.022z" id="mainIconPathAttribute" fill="green"></path> </svg>
    <% end %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<%= turbo_frame_tag line_item do %>
  <div class="line-item">
    <div class="line-item__name">
      <%= line_item.name %>
      <div class="line-item__description">
        <%= simple_format line_item.description %>
      </div>
    </div>
    <div class="line-item__quantity-price">
      <%= line_item.quantity %>
      &times;
      <%= number_to_currency line_item.unit_price %>
    </div>
    <div class="line-item__quantity">
      <%= line_item.quantity %>
    </div>
    <div class="line-item__price">
      <%= number_to_currency line_item.unit_price %>
    </div>
    <div class="line-item__actions">
      <%= button_to [quote, line_item_date, line_item],
                  method: :delete,
                  class: "flex flex-col items-center justify-center px-4 py-2 bg-gray-200 hover:bg-gray-300 text-gray-800 text-sm font-medium rounded-md" do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16"> <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
          <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
        </svg>
        Delete
      <% end %>
      <%= link_to [:edit, quote, line_item_date, line_item],
                class: "flex flex-col items-center justify-center px-4 py-2 bg-gray-200 hover:bg-gray-300 text-gray-800 text-sm font-medium rounded-md" do %>
        <svg width="24" stroke-width="1.5" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M20 12V5.74853C20 5.5894 19.9368 5.43679 19.8243 5.32426L16.6757 2.17574C16.5632 2.06321 16.4106 2 16.2515 2H4.6C4.26863 2 4 2.26863 4 2.6V21.4C4 21.7314 4.26863 22 4.6 22H11" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/> <path d="M8 10H16M8 6H12M8 14H11" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/> <path d="M16 5.4V2.35355C16 2.15829 16.1583 2 16.3536 2C16.4473 2 16.5372 2.03725 16.6036 2.10355L19.8964 5.39645C19.9628 5.46275 20 5.55268 20 5.64645C20 5.84171 19.8417 6 19.6464 6H16.6C16.2686 6 16 5.73137 16 5.4Z" fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/> <path d="M17.9541 16.9394L18.9541 15.9394C19.392 15.5015 20.102 15.5015 20.5399 15.9394V15.9394C20.9778 16.3773 20.9778 17.0873 20.5399 17.5252L19.5399 18.5252M17.9541 16.9394L14.963 19.9305C14.8131 20.0804 14.7147 20.2741 14.6821 20.4835L14.4394 22.0399L15.9957 21.7973C16.2052 21.7646 16.3988 21.6662 16.5487 21.5163L19.5399 18.5252M17.9541 16.9394L19.5399 18.5252" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/>
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
        </svg>
        Edit
      <% end %>
    </div>
  </div>
<% end %>

app/views/line_items/destroy.turbo_stream.erb
<%= turbo_stream.remove @line_item %>
<%= render_turbo_stream_flash_messages %>
<%= turbo_stream.update dom_id(@quote, :total) do %>
  <%= render "quotes/total", quote: @quote %>
<% end %>

app/views/quotes/_empty_state.html.erb
<div class="empty-state empty-state--only-child p-4 rounded-md border border-dashed text-center">
  <p class="p-4 text-lg text-[#292828] m-6 font-bold">
    You don't have any quotes yet!
  </p>
  <%= link_to "Add quote", new_quote_path, class: "inline-block bg-origin-border bg-transparent border-2 font-bold cursor-pointer p-1 m-2 rounded-1.5
                         transition ease-in-out duration-500 text-black bg-[#00000021] hover:bg-[#00000066] border-black",
                         data: { turbo_frame: dom_id(Quote.new) }  %>
</div>

app/views/quotes/create.turbo_stream.erb
<%= turbo_stream.prepend "quotes", @quote %>
<%= turbo_stream.update Quote.new, "" %>
<%= render_turbo_stream_flash_messages %>